# Generated by Django 5.0 on 2023-12-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='death_of_birth',
            new_name='date_of_death',
        ),
    ]
